Rails.application.routes.draw do
  resources :users
  resources :courses
  root to: 'pages#home'
  
  # RESTful Routes (generated by scaffold)

  # TODO: sessions routes (see /controllers/sessions_controller.rb)
  # login points to session controller - new method
  # logout points to session controller - destroy method
  # TODO: add/drop courses routes (see /controllers/registrations_controller.rb)

  post '/login', to: 'sessions#create'
  get '/login', to: 'sessions#new'
  delete '/logout', to: 'sessions#destroy'

  post '/add_course/:user_id/:course_id', to: 'registrations#add_course', as: 'add_course'
  delete '/drop_course/:user_id/:course_id', to: 'registrations#drop_course', as: 'drop_course'

end
